Parameters:
  ExportStackName:
    Type: 'String'
    Description: 'Stackname for VPC Subnet Import'
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName # AWS-Specific Parameter Types
    ConstraintDescription: "Must be the name of an existing EC2 KeyPair."

Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0bdb828fd58c52235'
      InstanceType: 't2.micro'
      KeyName: !Ref 'KeyPairName'
      SubnetId:
          Fn::ImportValue: !Sub '${ExportStackName}-PublicSubnetAZ1'
      # If this were not using !Sub you could use
      # SubnetId: !ImportValue 'NameOfStackExport'
